# Generated by Django 3.2.9 on 2021-12-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=150, verbose_name='ФИО'),
        ),
    ]
