# Generated by Django 3.2.9 on 2021-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_designform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designform',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Изображение'),
        ),
    ]
