# Generated by Django 3.2.9 on 2021-12-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_designform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='designform',
            name='image',
            field=models.ImageField(upload_to='upload/', verbose_name='Изображение'),
        ),
    ]
