# Generated by Django 3.2.9 on 2021-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211213_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designform',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
