# Generated by Django 3.2.9 on 2021-12-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211214_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
