# Generated by Django 3.2.9 on 2021-12-15 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_designform_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/', verbose_name='Изображение')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.designform', verbose_name='Заявки')),
            ],
            options={
                'verbose_name': 'Дополнительные фото',
                'verbose_name_plural': 'Дополнительные фото',
            },
        ),
        migrations.CreateModel(
            name='AddCommentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150, verbose_name='Комментарий')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.designform', verbose_name='Заявки')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарий',
            },
        ),
    ]
