# Generated by Django 4.0.1 on 2022-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_addcommentary_addimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='designform',
            name='imagecanc',
            field=models.ImageField(blank=True, upload_to='upload/', verbose_name='Изображение для удаления'),
        ),
    ]
