# Generated by Django 4.0.1 on 2022-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_designform_imagecanc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designform',
            name='status',
            field=models.CharField(choices=[('1', 'Новая'), ('2', 'Принято в работу'), ('3', 'Выполнено'), ('4', 'Отмена')], default=1, max_length=1),
        ),
    ]
